server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: spring-web

redis:
  host: 127.0.0.1
  port: 6379
  jedis:
    pool:
      max-idle: 8
      min-idle: 0

  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html



